[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
memechan_sol = "HvGgKbPfar5eUAnE5gnq5NvFdJRMVo39PFjJ4Hhe5FGk"

[programs.devnet]
memechan_sol = "HvGgKbPfar5eUAnE5gnq5NvFdJRMVo39PFjJ4Hhe5FGk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
# cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
