[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
memechan_sol = "CaR9ciDnNnE6WX35tZWrjeGdKUPaft7r4oQGF4JhwVxZ"

[programs.devnet]
memechan_sol = "CaR9ciDnNnE6WX35tZWrjeGdKUPaft7r4oQGF4JhwVxZ"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "https://api.devnet.solana.com"
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.genesis]]
address = "Eo7WjKq67rjJQSZxS6z3YkapzY3eMj6Xy8X5EQVn5UaB"
program = "tests/programs/mainnet/meteora-dynamic-amm.so"

[[test.genesis]]
address = "24Uqj9JCLxUeoC3hGfh5W3s9FM9uCHDS2SG3LYwBpyTi"
program = "tests/programs/mainnet/meteora-vault.so"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"  
program = "tests/programs/mainnet/mpl_metadata.so"

[[test.validator.clone]]
address = "59uVEJ3baADZ7Pg79MtV1erDrqGXYQK7qqJg3JwjGgm3"
[[test.validator.clone]]
address = "CYjqBp55ZEm2HRoMmjm2NgQxxYMz2rYAVcdaaUXCyQHW"
[[test.validator.clone]]
address = "DDD9b1Exy75uLzKTshTWftWa8Z96tvXhcMiuu8zBsRU4"
[[test.validator.clone]]
address = "HiUyuwe4Uezuqq4mhGqugdzVQT3mA3ZzBQsUW2x1H3Ri"

