[toolchain]

[features]
seeds = false
skip-lint = false
dev = true

[programs.localnet]
memechan_sol = "BDRDLhqbfEQx2LZQ9Js7k1Dt1S9AArTw44q1rM96YrwC"

[programs.devnet]
memechan_sol = "BDRDLhqbfEQx2LZQ9Js7k1Dt1S9AArTw44q1rM96YrwC"

[registry]
# url = "https://api.apr.dev"
url = "http://127.0.0.1:8899"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 1000

# [[test.genesis]]
# address = "HWy1jotHpo6UqeQxx49dpYYdQB8wj9Qk9MdxwjLvDHB8"  
# program = "tests/programs/devnet/raydium.so"

# [[test.genesis]]
# address = "EoTcMgcDRTJVZDMZWBoU6rhYHZfkNTVEAfz3uUJRcYGj"  
# program = "tests/programs/devnet/openbook.so"

[[test.genesis]]
address = "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8"  
program = "tests/programs/mainnet/raydium.so"

[[test.genesis]]
address = "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX"  
program = "tests/programs/mainnet/openbook.so"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"  
program = "tests/programs/devnet/mpl_metadata.so"

[[test.validator.account]]
address = "8QN9yfKqWDoKjvZmqFsgCzAqwZBQuzVVnC388dN5RCPo"
filename = "tests/state/amm-config.json"

# [[test.validator.account]]
# address = "3XMrhbv989VxAMi3DErLV9eJht1pHppW5LbKxe9fkEFR"
# filename = "tests/state/fee-destination-devnet.json"

[[test.validator.account]]
address = "7YttLkHDoNj9wyDur5pM1ejNaAvT9X4eqaYcHQqtj2G5"
filename = "tests/state/fee-destination-mainnet.json"

[[test.validator.account]]
address = "2immgwYNHBbyVQKVGCEkgWpi53bLwWNRMB5G2nbgYV17"
filename = "tests/state/lookup-table-mainnet.json"