[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
memechan_sol = "EWsBchGns4n9dtcsBvByHRfHhZ2iseNkjA3CsEUaGZFo"

[programs.devnet]
memechan_sol = "EWsBchGns4n9dtcsBvByHRfHhZ2iseNkjA3CsEUaGZFo"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "https://api.devnet.solana.com"
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000

[test.validator]
url = "https://api.devnet.solana.com"

[[test.genesis]]
address = "CPMDWBwJDtYax9qW7AyRuVC19Cc4L4Vcy4n2BHAbHkCW"
program = "tests/programs/devnet/raydium-cpmm.so"

[[test.genesis]]
address = "adMCyoCgfkg7bQiJ9aBJ59H3BXLY3r5LNLfPpQfMzBe"
program = "tests/programs/devnet/raydium.so"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"  
program = "tests/programs/devnet/mpl_metadata.so"

[[test.validator.clone]]
address = "HX2pp5za2aBkrA5X5iTioZXcrpWb2q9DiaeWPW3qKMaw"
[[test.validator.clone]]
address = "3XMrhbv989VxAMi3DErLV9eJht1pHppW5LbKxe9fkEFR"
[[test.validator.clone]]
address = "3XT1xcsgwjrfsBpQNeYcDhNj9NGJFzGjGAqfx6UWvhjk"
[[test.validator.clone]]
address = "8QN9yfKqWDoKjvZmqFsgCzAqwZBQuzVVnC388dN5RCPo"
[[test.validator.clone]]
address = "75q3G81vDnyzfwK87GiPxAjAAYytYotqaTdTw3vqWMnp"
[[test.validator.clone]]
address = "9zSzfkYy6awexsHvmggeH36pfVUdDGyCcwmjT3AQPBj6"
[[test.validator.clone]]
address = "G11FKBRaAkHAKuLCgLM6K6NUc9rTjPAznRCjZifrTQe2"



