[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
memechan_sol = "EWsBchGns4n9dtcsBvByHRfHhZ2iseNkjA3CsEUaGZFo"

[programs.devnet]
memechan_sol = "EWsBchGns4n9dtcsBvByHRfHhZ2iseNkjA3CsEUaGZFo"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "https://api.devnet.solana.com"
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
