[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
memechan_sol = "CaR9ciDnNnE6WX35tZWrjeGdKUPaft7r4oQGF4JhwVxZ"
meme_custodian = "AiTSMBoBUHfnGybUHUCMQyu9y4gwmznnrTXz5Dr97LtW"

[programs.devnet]
memechan_sol = "CaR9ciDnNnE6WX35tZWrjeGdKUPaft7r4oQGF4JhwVxZ"
meme_custodian = "AiTSMBoBUHfnGybUHUCMQyu9y4gwmznnrTXz5Dr97LtW"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "https://api.devnet.solana.com"
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run jest --detectOpenHandles --forceExit"

[test]
startup_wait = 10000

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.genesis]]
address = "Eo7WjKq67rjJQSZxS6z3YkapzY3eMj6Xy8X5EQVn5UaB"
program = "tests/programs/mainnet/meteora-dynamic-amm.so"

[[test.genesis]]
address = "24Uqj9JCLxUeoC3hGfh5W3s9FM9uCHDS2SG3LYwBpyTi"
program = "tests/programs/mainnet/meteora-vault.so"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/programs/mainnet/mpl_metadata.so"

