[package]
name = "amm"
version = "2.0.1"
description = "Deposit liquidity to earn fees and swap between mints"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "amm"

[features]
cpi = ["no-entrypoint"]
default = []
dev = []
no-entrypoint = []
no-idl = []
no-log-ix-name = []

[dependencies]
anchor-lang = "0.29.0"
anchor-spl = "0.29.0"
decimal = { path = "../solana-decimal" }

[dev-dependencies]
criterion = "0.3"
pretty_assertions = "1.2"
proptest = "1.0"
rand = "0.8"
serial_test = "0.6"
solana-sdk = "*" # whatever anchor uses
