[package]
name = "memechan-sol"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "memechan_sol"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []

[dependencies]
anchor-lang = "0.29.0"
anchor-spl = "0.29.0"
solana-program = "*"
num-integer = "0.1.46"
uint = "0.9.5"
# amm = { path = "../../deps/amm", features = ["cpi"] }
# amm = { git = "https://github.com/aldrin-labs/amm.git", features = ["cpi"] }

